apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  REDIS_PASSWORD: "changeme-in-production"
  SECRET_KEY: "flask-secret-key-change-in-prod"
